### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by fcollonval** [MMesch/labextension_tutorial#2]
Hey @MMesch I know that this is a bit outdated. But I think it is a great start for tutorials as discuss [there](https://discourse.jupyter.org/t/brainstorming-for-a-more-detailed-extension-development-tutorial/2493/6). Could you please add a license to know if this work can be reused?
Cheers

**Comment by MMesch** [comment]
I added a public domain license! Feel free to use as you want. I am happy about attribution, but it isn't required at all if it is cumbersome.
